apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifest:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: meanderingtowardsoblivion/auth
      context: auth
      docker:
        docker: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
